### ISSUE TITLE
hash_to_ec

### ISSUE THREAD

**Issue by fanatid** [monero-project/mininero#2]
Why [hash_to_ec](https://github.com/monero-project/mininero/blob/9bcf099ce4d7b3e94e653c27a2e2352df697fa8f/mininero.py#L359) is different from [hash_to_ec in bitmonero](https://github.com/monero-project/bitmonero/blob/1c66fe04bcebf50102abe6c96322f0fa5ce740ec/src/crypto/crypto.cpp#L245)?
(`ge_scalarmult_base` instead `ge_fromfe_frombytesvartime`)

**Comment by othexmr** [comment]
Hey fanatid, this was just for testing back then and is incorrect for real world use, this repo is dicarded the new Mininero versions are found here: https://github.com/ShenNoether/MiniNero

And here is a writeup about ge_fromfe, what it does and why we need to use it in monero: https://github.com/ShenNoether/ge_fromfe_writeup

**Comment by fanatid** [comment]
@othexmr thanks for answer! Would be nice if you write about new mininero in this repository.

**Comment by fanatid** [comment]
I checked https://github.com/ShenNoether/MiniNero , hash to point also different there https://github.com/ShenNoether/MiniNero/blob/master/MiniNero.py#L305
(result is just point recovering from hash in loop)

**Comment by ghost** [comment]
@fanatid, please see this line https://github.com/ShenNoether/MiniNero/blob/master/MiniNero.py#L238 for the function actually used by monero.

**Comment by ghost** [comment]
@fanatid, the comments on the lines you have linked are probably for a previous version.. (This is a my prototyping repo, so I'm not excruciatingly careful about the comments/ etc).

**Comment by fanatid** [comment]
@ShenNoether oh, I see, it's looks like C code, probably I skipped this code somehow :(
Thank you!

**Comment by ghost** [comment]
@fanatid, your welcome
